### ISSUE TITLE
Unable to connect to local k3s cluster

### ISSUE THREAD

**Issue by spacebat** [mruoss/kino_k8s#94]
Hi, love your work, this is a great idea. I'm using the same ~/.kube/k3s.yml (a kubernetes config) that works with kubectl to access a locally installed k3s cluster, however with kino_k8s I get this logged:

```
10:07:14.592 [error] Process #PID<0.2049.0> on node :"nghvqep3-livebook_gsabyd4w@medusa" raised an exception
** (MatchError) no match of right hand side value: {:error, %K8s.Client.HTTPError{message: "HTTP Error 503", adapter_specific_error: nil}}
    (kino_k8s 1.2.1) lib/kino_k8s/resource_gvk_cache.ex:97: anonymous fn/3 in KinoK8s.ResourceGVKCache.load_gvks/3
    (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (kino_k8s 1.2.1) lib/kino_k8s/resource_gvk_cache.ex:96: anonymous fn/3 in KinoK8s.ResourceGVKCache.load_gvks/3
```

The connection smart cell does return a conn:
```
%K8s.Conn{
  auth: K8s.Conn.Auth.Certificate<...>,
  url: "https://127.0.0.1:6443",
  cacertfile: "~/.cache/mix/installs/elixir-1.15.6-erts-14.0.2/170c5018437d0ffff816384e64da70c0/_build/dev/lib/castore/priv/cacerts.pem",
  http_provider: K8s.Client.MintHTTPProvider,
  discovery_driver: K8s.Discovery.Driver.HTTP,
  discovery_opts: [],
  namespace: nil,
  middleware: %K8s.Middleware.Stack{
    request: [
      K8s.Middleware.Request.Initialize,
      K8s.Middleware.Request.EncodeBody
    ],
    response: []
  },
  cluster_name: "default",
  user_name: "default",
  insecure_skip_tls_verify: true,
  ca_cert: <<48, 130, 1, 118, 48, 130, 1, 29, 160, ...>>
}
```

However subsequent cells using this conn either crash (connect to pod) or return nil (get/list/watch). I'm using "Insecure Skip TLS Verify" because without it the ssl handshake fails (k3s self-signed cert I guess).

This same kube config file works with the k8s elixir package version 2.5.0 to list deployments from this cluster and I haven't seen that error there.

This is the case with version 1.0 of this package and the latest from the main branch.

**Comment by mruoss** [comment]
Hi @spacebat 
This is very strange. HTTP Error 503 is returned by the cluster. I don't know why but it doesn't look like it's got to do with `kino_k8s`. 

> This same kube config file works with the k8s elixir package version 2.5.0 to list deployments from this cluster and I haven't seen that error there.

The smart cells of `kino_k8s` generate code. You can see it if you click on the code icon (`<>`). Can you copy that code and run it in your k8s setup? For both, the Conn and the actual operations. `kino_k8s` is just a "visual wrapper" around `k8s`. It's using plain `k8s` under the hood...

>  I'm using "Insecure Skip TLS Verify" because without it the ssl handshake fails (k3s self-signed cert I guess).

Yeah this is WIP in the OTP (see https://github.com/erlang/otp/issues/7968 and https://github.com/erlang/otp/pull/7974)
